index:
	@if [ -f Log/log.dat ]; then \
		rm Log/log.dat; \
	fi
	gcc -o executavel *.c -g
	clear
	./executavel

clear:
	@if [ -f executavel ]; then \
		rm executavel; \
	fi
	@if [ -f Log/log.dat ]; then \
		rm Log/log.dat; \
	fi
	clear
